spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_album?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
#    url: jdbc:mysql://106.15.51.67:3306/db_album?userSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: qiangzi1986